# TODO Expose HTTPS 
# TODO Rename component
# TODO Create .env
services:
  server:
    container_name: Server
    image: projectmanagerserver
    build:
      context: .
      dockerfile: ProjectManager_Server/Dockerfile
    expose:
      - "5000"
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - database
    networks:
      - internal

  database:
    container_name: database
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ProjectManager
      POSTGRES_USER: toto
      POSTGRES_PASSWORD: Toto123*
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - internal

networks:
  internal:

volumes:
  database: